# Generated by Django 4.2.1 on 2023-05-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_currency', models.CharField(choices=[('usd', 'USD'), ('eur', 'EUR'), ('egp', 'EGP')], max_length=5)),
                ('target_currency', models.CharField(choices=[('usd', 'USD'), ('eur', 'EUR'), ('egp', 'EGP')], max_length=5)),
                ('number_of_requests', models.IntegerField(default=0)),
            ],
        ),
    ]
